apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: init-db
          image: docker.io/bitnami/postgresql:11.8.0-debian-10-r5
          command:
            [
              "sh",
              "-c",
              'until pg_isready -h postgresql -d coorseo -U postgres -p 5432; do echo waiting for postgres; sleep 2; done;',
            ]
#        - name: init-db-structure
#          image: docker.io/coorseoadmin/coorseo:develop
#          env:
#            - name: SQLALCHEMY_DATABASE_URI
#              value: postgresql+psycopg2://postgres:EDqFPatXr6@postgresql:5432/coorseo
#          command: ["python3.8", "/coorseo-api/migration.py", "db", "upgrade"]
      containers:
        - name: application
          image: docker.io/coorseoadmin/coorseo:develop
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "2000m"
            requests:
              memory: "256Mi"
              cpu: "1000m"
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql+psycopg2://postgres:EDqFPatXr6@postgresql:5432/coorseo
            - name: SECRET_KEY
              value: HxGIR23yK41si8zd9t9kKTEzQu5IyWetsGzrKtPCe294P4ACyselq4McFarahci
            - name: SESSION_COOKIE_NAME
              value: my_cookie